version: '3.8'
services:
  postgres:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - '5432:5432'

volumes:
  postgres:
